name: graphic
description: A data visualization (charts / chart / charting) library based on Grammar of Graphics.
version: 0.3.0
homepage: https://github.com/entronad/graphic

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.0.8
  intl: ^0.16.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
